# Generated by Django 6.0.5 on 2026-05-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_window_days', models.PositiveIntegerField(default=7)),
                ('scan_frequency_hours', models.PositiveIntegerField(default=6)),
                ('notify_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('notify_via_email', models.BooleanField(default=False)),
                ('notify_email_address', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Scan settings',
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=200, unique=True)),
                ('sender', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=1000)),
                ('snippet', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('confidence', models.FloatField()),
                ('is_scam', models.BooleanField()),
                ('labeled_in_gmail', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['is_scam', 'received_at'], name='dashboard_e_is_scam_3469a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_scams', models.PositiveIntegerField()),
                ('top_senders', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['period', 'generated_at'], name='dashboard_s_period_3220fb_idx')],
            },
        ),
    ]
