# Generated by Django 6.0.5 on 2026-05-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_emailrecord_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='user_risk_override',
            field=models.CharField(blank=True, choices=[('legit', 'Legit'), ('possible_scam', 'Possible scam'), ('scam', 'Scam')], default='', max_length=20),
        ),
    ]
